language: r
warnings_are_errors: true

r:
  - release
  - devel

r_binary_packages:
  - XML
  - xml2
  - stringr
  - testthat
  - covr

after_success:
  - Rscript -e 'library(covr) ; codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
